Updates to support newer kernels
embeddedarm/ts4900-utils pull request #7
Opened 2024-09-05 17:58 UTC by markfeathers

Replaces all sysfs gpio with libgpiod.
deprecate gpioctl, nvramctl, load_fpga, adc8390 which are are not needed with newer kernels.
added clang-format & synced all code to it
dos2unix on ispvm.c/h

2024-09-05 18:27 UTC, randytsi369 approved these changes
Reviewed, not tested.

2024-09-05 18:37 UTC, ts-kris requested changes

2024-09-05 18:37 UTC, ts-kris commented on src/fpga.c
> +			char path[512], busname[512];
Since we're touching these, this should use `PATH_MAX` and `NAME_MAX`

2024-09-05 18:37 UTC, ts-kris commented on src/fpga.c
> +			snprintf(path, 512, "/sys/bus/i2c/devices/%s/name", dir->d_name);
These should use `sizeof()` so no matter what the actual length is over time, it is correctly calculated. And, if we're using `NAME_MAX` and `PATH_MAX`, using `sizeof()` is better as it prevents copy/paste errors. e.g. you don't want to use `PATH_MAX` on a read of what should be `NAME_MAX`, but always using `sizeof()` will correctly resolve.

Do this in multiple places, I won't comment for each

2024-09-05 18:37 UTC, ts-kris commented on src/isl12020rtc.c
> +			char path[512], busname[512];
See previous comments on `PATH_MAX`, `NAME_MAX`, and `sizeof()` use for these

2024-09-05 18:37 UTC, ts-kris commented on script/tssilomon
> +GPIOLINE="4"
Since you are using `gpioget`, it should be possible to make this more generic and look up the pin directly by name, e.g.

`gpioget $(gpiofind "POWER_FAIL")` (or whatever the actual line name is)

You could also do like:
`powerfailgpio=$(gpiofind "POWER_FAIL")`

And now have the proper chip/line stored in the one variable. `gpioget "${powerfailgpio}"`

2024-09-05 18:37 UTC, ts-kris commented on script/tssilomon
> +if ! gpioget $GPIOCHIP $GPIOLINE >/dev/null 2>&1; then
Did you run `shellcheck` against this? I feel like this line would get complaints. With the above, it probably should look something like

```
gpioget $(gpiofind "POWER_FAIL") >/dev/null 2>&1
RET=$?
if [ ${RET} -ne 0 ]; then
...
```

2024-09-05 18:37 UTC, ts-kris commented on script/tssilomon
> +	if [ "$gpio_value" -ne 1 ]; then
I can't remember exactly, but I think if you are comparing numerical values, you don't want `gpio_value` wrapped in quotes?

2024-09-05 18:37 UTC, ts-kris commented on script/tssilomon
> +	sleep 0.5
If you're making this change, do the same on line 41

2024-09-05 18:37 UTC, ts-kris commented on src/isl12020rtc.c
> +#define ISL12022_OFF_CTL_FLASH (1 << 2) /* 1 to commit to flash, 0 to just ram */
IMO, I'm not a fan of the misaligned define values that this `.clang-format` produces. Kernel format has the values all aligned. Change it, or don't, just expressing my opinion.

2024-09-05 18:37 UTC, ts-kris commented on src/tshwctl.c
> +		{ "set", 0, 0, 's' },  { "dump", 0, 0, 'c' }, { "showall", 0, 0, 'q' },	 { "help", 0, 0, 'h' },
IMO not a fan of this format, easier to match long_opts and usage as 1:1 as possible to make it easier to find and match things at a glance. Change it, or don't, just my opinion.

2024-09-05 19:08 UTC, luckshot approved these changes

2024-10-03 21:28 UTC, ts-kris approved these changes

2024-10-03 21:29 UTC, merged